### ISSUE TITLE
Level Editor: Undergrowth seems to be broken with default settings + doesn't show up in game or save in the terrain file

### ISSUE THREAD

**Issue by GyalayPaul** [jkulawik/bunker-issues#14]
In the performance settings, there's a custom undergrowh fade option, but the start value seems to be broken and always starts on a negative number, so it's never visible. 
It's possible to disable custom undergrowh fade start, which leaves level designers with no control on the rendering distance of the undergrowth, in order to see it in the editor, but it still won't show up ingame. It also seems like most undergrowth in the bunker is made out of entities, and not actual udnergrowth.

**Comment by GyalayPaul** [comment]
Did a bit more testing, it doesn't seem to save at all in the terrain map file, and upon reload it's gone.

**Comment by GyalayPaul** [comment]
Partially fixed on the public beta branch as of 29/06/2023 , the undergrowth is now saved properly, however:

The input text fields and the sliders for custom undergrowth distance don't seem to do anything, but they can be edited manually through the LevelEditor.prf file in the HPL folder.

**Comment by jkulawik** [comment]
Maybe let's close this and open an issue that's dedicated to the render distance thing?
