### ISSUE TITLE
Level Editor: can't select and place static objects in zoomed out view

### ISSUE THREAD

**Issue by GyalayPaul** [jkulawik/bunker-issues#15]
![image](https://github.com/jkulawik/bunker-issues/assets/12644719/fd3eefe9-24f4-4386-a185-48e87a41951f)

**Comment by jkulawik** [comment]
"Sometimes when trying to select a static object when using the zoomed out view (ctrl scrolwheel on the thumbnails) , you are unable to select and place items from the list."

**Comment by GyalayPaul** [comment]
Still occurs as of the public beta of 29/06/2023.

**Comment by jkulawik** [comment]
I can't reproduce this, might be fixed

**Comment by GyalayPaul** [comment]
Can't reproduce on latest as well , maybe this should be closed
