### ISSUE TITLE
Level Editor: Entity EffectBrightnessMul and IllumBrightness sliders don't work, only the text field works. 

### ISSUE THREAD

**Issue by GyalayPaul** [jkulawik/bunker-issues#23]
![image](https://github.com/jkulawik/bunker-issues/assets/12644719/931501eb-064d-4c81-92cd-d4bec1139886)
Can't use arrows or the slider, can only input values via the text field

**Comment by AndrewIsGreen** [comment]
I was in the editor at the time and gave this a try. Spawned an entity and played with the EffectBrightnessMul, and IllumBrightness sliders. The sliders, arrows, and text field all work for me. This is from a fresh install of the bunker on steam at the time this is posted.

https://github.com/jkulawik/bunker-issues/assets/13738394/e098f129-4467-4162-a193-66c21a22487d

**Comment by jkulawik** [comment]
Luis says he might have indeed fixed this. Thanks for testing!
