### ISSUE TITLE
Level Editor: sliders for custom undergrowth distance don't seem to work

### ISSUE THREAD

**Issue by jkulawik** [jkulawik/bunker-issues#25]
Separated out of #14.

> The input text fields and the sliders for custom undergrowth distance don't seem to do anything, but they can be edited manually through the LevelEditor.prf file in the HPL folder.

**Comment by jkulawik** [comment]
I'm not sure if this is what you meant, but:
The sliders, the buttons and the text input do work in that the values get saved to config upon quitting the editor. Whether it changes the actual render distances in the editor I can't really figure out.

**Comment by GyalayPaul** [comment]
Seems to have been fixed on the current version of the editor
