### ISSUE TITLE
Level Editor: rigged models are invisible and can't be selected

### ISSUE THREAD

**Issue by jkulawik** [jkulawik/bunker-issues#3]
Multiple models don't render in the editor, or render only at a far distance and/or specific angle of the camera.

This "seems to happen to any entity with a skeleton rig like cables, corpses, rigged items, and the arsenal nets".

Also seems to include:
- chains
- weapons
- flashlight
- flares

Related to camera culling.

**Comment by jkulawik** [comment]
If the proprieties of the rigged items are changed, they become both visible and selectable (see https://github.com/jkulawik/bunker-issues/issues/5) again.

**Comment by GyalayPaul** [comment]
Seems to be fixed as of the current public beta branch version (29/06/2023)
