### ISSUE TITLE
Level Editor: can't load any custom soundbanks

### ISSUE THREAD

**Issue by jkulawik** [jkulawik/bunker-issues#6]
Title.

**Comment by frictional-luis** [comment]
Hey hey, can you please post some offending data? Thanks!

**Comment by jkulawik** [comment]
Should be fixed as of [v1.15](https://frictionalgames.com/2023-07-amnesia-the-bunker-second-update-1-15/)

**Comment by AndrewIsGreen** [comment]
The level editor can detect a soundbank I created with custom sounds.

![image](https://github.com/jkulawik/bunker-issues/assets/13738394/84941c13-c59a-486f-8494-afd069d3b0e8)

**Comment by jkulawik** [comment]
Thanks for testing
